name: Launch Micro AMD Instance

on:
  workflow_dispatch:

jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OCI CLI
        run: |
          python3 -m pip install --upgrade pip setuptools
          pip install oci-cli

      # Özel anahtarı senin secret isminle (OCI_PRIVATE_KEY) yazdırıyoruz
      - name: Setup OCI Config
        env:
          OCI_KEY_CONTENT: ${{ secrets.OCI_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.oci
          
          python3 -c "import os; open('/home/runner/.oci/oci_api_key.pem', 'w').write(os.environ['OCI_KEY_CONTENT'].strip() + '\n')"
          chmod 600 ~/.oci/oci_api_key.pem

          cat <<EOF > ~/.oci/config
          [DEFAULT]
          user=${{ secrets.OCI_USER_OCID }}
          fingerprint=${{ secrets.OCI_FINGERPRINT }}
          key_file=/home/runner/.oci/oci_api_key.pem
          tenancy=${{ secrets.OCI_TENANCY_OCID }}
          region=${{ secrets.OCI_REGION }}
          EOF
          chmod 600 ~/.oci/config

      - name: Fetch AMD Compatible Image & Launch
        id: launch_vm
        env:
          SUPPRESS_LABEL_WARNING: "True"
          OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING: "True"
          SSH_KEY_CONTENT: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
        run: |
          python3 -c "import os; open('ssh_key.pub', 'w').write(os.environ['SSH_KEY_CONTENT'].strip() + '\n')"

          AMD_IMAGE_ID=$(oci compute image list \
            --compartment-id "${{ secrets.OCI_COMPARTMENT_OCID }}" \
            --operating-system "Canonical Ubuntu" \
            --operating-system-version "22.04 Minimal" \
            --shape "VM.Standard.E2.1.Micro" \
            --query "data[0].id" \
            --raw-output)

          echo "Bulunan AMD İmaj ID: $AMD_IMAGE_ID"

          oci compute instance launch \
            --availability-domain "LHiX:EU-FRANKFURT-1-AD-1" \
            --compartment-id "${{ secrets.OCI_COMPARTMENT_OCID }}" \
            --shape "VM.Standard.E2.1.Micro" \
            --subnet-id "${{ secrets.OCI_SUBNET_ID }}" \
            --image-id "$AMD_IMAGE_ID" \
            --display-name "micro-runner-vm" \
            --assign-public-ip true \
            --ssh-authorized-keys-file ssh_key.pub

      - name: Send Success Telegram Notification
        if: steps.launch_vm.outcome == 'success'
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=🚀 *AMD Micro Sunucun Başarıyla Kuruldu!*%0A%0AMicro VM aktif duruma geldi." \
            -d "parse_mode=Markdown"
