name: Launch Micro AMD Instance

on:
  workflow_dispatch: # Manuel tetiklemek için

jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install OCI CLI
        run: |
          python3 -m pip install --upgrade pip setuptools
          pip install oci-cli

      - name: Setup OCI Config
        run: |
          mkdir -p ~/.oci
          
          cat << 'EOF' > ~/.oci/oci_api_key.pem
          ${{ secrets.OCI_PRIVATE_KEY }}
          EOF
          chmod 600 ~/.oci/oci_api_key.pem

          cat <<EOF > ~/.oci/config
          [DEFAULT]
          user=${{ secrets.OCI_USER_OCID }}
          fingerprint=${{ secrets.OCI_FINGERPRINT }}
          key_file=/home/runner/.oci/oci_api_key.pem
          tenancy=${{ secrets.OCI_TENANCY_OCID }}
          region=${{ secrets.OCI_REGION }}
          EOF
          chmod 600 ~/.oci/config

      - name: Launch Oracle AMD Micro Instance
        id: launch_vm
        env:
          SUPPRESS_LABEL_WARNING: "True"
          OCI_CLI_SUPPRESS_FILE_PERMISSIONS_WARNING: "True"
        run: |
          cat << 'EOF' > ssh_key.pub
          ${{ secrets.OCI_SSH_PUBLIC_KEY }}
          EOF

          oci compute instance launch \
            --availability-domain "LHiX:EU-FRANKFURT-1-AD-1" \
            --compartment-id "${{ secrets.OCI_COMPARTMENT_OCID }}" \
            --shape "VM.Standard.E2.1.Micro" \
            --subnet-id "${{ secrets.OCI_SUBNET_ID }}" \
            --image-id "${{ secrets.OCI_IMAGE_ID }}" \
            --display-name "micro-runner-vm" \
            --assign-public-ip true \
            --ssh-authorized-keys-file ssh_key.pub

      - name: Send Success Telegram Notification
        if: steps.launch_vm.outcome == 'success'
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d "text=🚀 *AMD Micro Sunucun Başarıyla Kuruldu!*%0A%0AMicro VM aktif duruma geldi." \
            -d "parse_mode=Markdown"
